site_name: DAPLAB Official Documentation
pages:
- Home: 'index.md'
- User Documentation:
    - 'Getting Started': 'getting_started.md'
    - 'DAPLAB Architecture': 'architecture.md'

- Tutorials:
    - 'HDFS Tutorial': 'tutorial_hdfs.md'
    - 'Hive Tutorial': 'tutorial_hive.md'
    - 'Pig Tutorial': 'tutorial_pig.md'
    - 'Spark Tutorial': 'tutorial_spark.md'
    - 'Kafka Tutorial': 'tutorial_kafka.md'
    - 'Cassandra Tutorial': 'tutorial_cassandra.md'
    - 'All Tutorials': 'tutorial_all.md'

- Projects:
    - 'Zefix Project': 'project_zefix.md'
    - 'SwissSim Project': 'project_swisssim.md'
    - 'Hive Auto Partitioner': 'project_hiveautopartitioner.md'
    
- Others:
    - 'Twitter API Credentials': 'twitter_account.md'
    - 'Ambari Cheat Sheet': 'ambari_cheat_sheet.md'

theme: bootstrap
site_favicon: logo.png

markdown_extensions:
    - extra
    - attr_list
    - footnotes
    
extra_css: 
    - daplab.css
