site_name: DAPLAB Official Documentation
pages:
- Home: 'index.md'
- User Documentation:
    - 'Getting Started': 'getting_started.md'
    - 'DAPLAB Architecture': 'architecture.md'
#    - 'Data Craftmanship': 'data_craftsmanship.md' TODO

- Tutorials:
    - 'All Tutorials': 'tutorials/index.md'
    - 'Cassandra': 'tutorials/cassandra.md'
    - 'HDFS': 'tutorials/hdfs.md'
    - 'Hive': 'tutorials/hive.md'
    - 'Kafka': 'tutorials/kafka.md'
    - 'Pig': 'tutorials/pig.md'
    - 'Spark': 'tutorials/spark.md'

- Projects:
    - 'All Projects': 'projects/index.md'
    - 'Highly available HTTPS': 'projects/https-ha.md'
    - 'Hive Auto Partitioner': 'projects/hiveautopartitioner.md'
    - 'HiveQLBot': 'projects/hive-ql-bot.md'
    - 'Notebook': 'projects/notebook.md'
    - 'Nutch Crawler': 'projects/nutch.md'
    - 'SwissSim Project': 'projects/swisssim.md'
    - 'Zefix Project': 'projects/zefix.md'

- Others:
    - 'Hacky Thursdays': 'hacky_thursdays.md'
    - 'Twitter API Credentials': 'twitter_account.md'
    - 'Ambari Cheat Sheet': 'ambari_cheat_sheet.md'

#theme: cosmo
theme: flatly
site_favicon: logo.png

markdown_extensions:
    - extra
    - attr_list
    - footnotes

extra_css:
    - daplab.css
